export const SERVER = __DEV__ ? "http://192.168.18.10/api/" : "http://144.2.164.8/api/"
export const URL_LOGIN = SERVER + "users";
export const URL_REGISTER = SERVER + "users/register";
export const URL_USER_REFRESH = SERVER + "users/refresh";
export const URL_USER_UPDATE = SERVER + "users/update";
export const URL_USER_PASSWORD = SERVER + "users/password";
export const URL_CREDIT_CARD_REGISTER = SERVER + "creditcard";
export const URL_CREDIT_CARD_UPDATE = SERVER + "creditcard/update";
export const URL_RESTAURANT = SERVER + "restaurants";
export const URL_BOOKINGS_SEARCH = SERVER + "bookings";
export const URL_BOOKINGS_REGISTER = SERVER + "bookings/register";
export const URL_FAVORITES = SERVER + "favorites";
export const URL_FAVORITES_REGISTER = SERVER + "favorites/register";
export const URL_FAVORITES_DELETE = SERVER + "favorites/delete";
